/**
 * Canonical Brawlhalla legend roster (68 entries) as of patch 10.07.
 * Source: https://www.brawlhalla.com/legends — scraped via
 * scripts/scrape-legends.mjs. Re-run that script when the roster grows.
 */
export interface RosterEntry {
  slug: string
  name: string
}

export const LEGEND_ROSTER: RosterEntry[] = [
  { slug: "bodvar", name: "Bödvar" },
  { slug: "cassidy", name: "Cassidy" },
  { slug: "orion", name: "Orion" },
  { slug: "lord-vraxx", name: "Lord Vraxx" },
  { slug: "gnash", name: "Gnash" },
  { slug: "queen-nai", name: "Queen Nai" },
  { slug: "hattori", name: "Hattori" },
  { slug: "sir-roland", name: "Sir Roland" },
  { slug: "scarlet", name: "Scarlet" },
  { slug: "thatch", name: "Thatch" },
  { slug: "ada", name: "Ada" },
  { slug: "sentinel", name: "Sentinel" },
  { slug: "lucien", name: "Lucien" },
  { slug: "teros", name: "Teros" },
  { slug: "brynn", name: "Brynn" },
  { slug: "asuri", name: "Asuri" },
  { slug: "barraza", name: "Barraza" },
  { slug: "ember", name: "Ember" },
  { slug: "azoth", name: "Azoth" },
  { slug: "koji", name: "Koji" },
  { slug: "ulgrim", name: "Ulgrim" },
  { slug: "diana", name: "Diana" },
  { slug: "jhala", name: "Jhala" },
  { slug: "kor", name: "Kor" },
  { slug: "wu-shang", name: "Wu Shang" },
  { slug: "val", name: "Val" },
  { slug: "ragnir", name: "Ragnir" },
  { slug: "cross", name: "Cross" },
  { slug: "mirage", name: "Mirage" },
  { slug: "nix", name: "Nix" },
  { slug: "mordex", name: "Mordex" },
  { slug: "yumiko", name: "Yumiko" },
  { slug: "artemis", name: "Artemis" },
  { slug: "caspian", name: "Caspian" },
  { slug: "sidra", name: "Sidra" },
  { slug: "xull", name: "Xull" },
  { slug: "kaya", name: "Kaya" },
  { slug: "isaiah", name: "Isaiah" },
  { slug: "jiro", name: "Jiro" },
  { slug: "lin-fei", name: "Lin Fei" },
  { slug: "zariel", name: "Zariel" },
  { slug: "rayman", name: "Rayman" },
  { slug: "dusk", name: "Dusk" },
  { slug: "fait", name: "Fait" },
  { slug: "thor", name: "Thor" },
  { slug: "petra", name: "Petra" },
  { slug: "vector", name: "Vector" },
  { slug: "volkov", name: "Volkov" },
  { slug: "onyx", name: "Onyx" },
  { slug: "jaeyun", name: "Jaeyun" },
  { slug: "mako", name: "Mako" },
  { slug: "magyar", name: "Magyar" },
  { slug: "reno", name: "Reno" },
  { slug: "munin", name: "Munin" },
  { slug: "arcadia", name: "Arcadia" },
  { slug: "ezio", name: "Ezio" },
  { slug: "tezca", name: "Tezca" },
  { slug: "thea", name: "Thea" },
  { slug: "red-raptor", name: "Red Raptor" },
  { slug: "loki", name: "Loki" },
  { slug: "seven", name: "Seven" },
  { slug: "vivi", name: "Vivi" },
  { slug: "imugi", name: "Imugi" },
  { slug: "king-zuva", name: "King Zuva" },
  { slug: "priya", name: "Priya" },
  { slug: "ransom", name: "Ransom" },
  { slug: "lady-vera", name: "Lady Vera" },
  { slug: "rupture", name: "Rupture" },
]
