import catalogue from "@/lib/skins-catalogue.json"

/**
 * The Brawlhalla skin catalogue, read from brawlhalla.wiki.gg.
 *
 * 673 skins across 69 legends in ~50KB of JSON, regenerated by
 * `node scripts/sync-skins.mjs`. A file rather than a table because it is
 * reference data that changes when Blue Mammoth ships a skin — a handful of
 * times a year — and a stale entry costs nothing worse than a skin missing from
 * the picker until someone reruns the script.
 *
 * **We store a URL, not an image.** `profiles.favorite_skin` has always been
 * `{ src, name }`, and the picker writes a wiki thumbnail URL into `src`, so
 * every surface that already renders a favorite skin — profile header, the
 * ranked card, the leaderboard podium — keeps working untouched. Nothing is
 * mirrored, so the catalogue costs no storage and no egress at all.
 *
 * The trade is a dependency on someone else's CDN for user-facing art. It is
 * cached (Cloudflare, 4h) and hotlinking works from a browser, but their
 * filenames are theirs to rename. The cheap hedge, when it matters, is to copy
 * the one chosen image into Blob on save — at most one per player who sets a
 * skin. Until then this is honest about what it is.
 */

const ORIGIN = "https://brawlhalla.wiki.gg"

export interface SkinEntry {
  /** Display name, e.g. "Astral Core". */
  name: string
  /** Wiki filename for the square icon — always present. */
  icon: string
  /** Wiki filename for the posed art. Absent for ~40% of skins. */
  art?: string
}

interface Catalogue {
  generatedAt: string
  legends: Record<string, SkinEntry[]>
}

const DATA = catalogue as Catalogue

/** Legends that have at least one skin, in roster-name form. */
export function skinLegends(): string[] {
  return Object.keys(DATA.legends)
}

export function skinsForLegend(legend: string): SkinEntry[] {
  return DATA.legends[legend] ?? []
}

export function catalogueDate(): string {
  return DATA.generatedAt
}

/**
 * A thumbnail of a wiki file at a given width.
 *
 * MediaWiki renders these on demand and Cloudflare caches them, which is what
 * keeps this cheap: the source art is 962x1280 at ~360KB, a 400px thumb is
 * ~168KB, and a 64px icon is ~8KB. Asking for the original would put a third of
 * a megabyte behind every profile header.
 */
export function wikiThumb(file: string, width: number): string {
  return `${ORIGIN}/images/thumb/${file}/${width}px-${file}`
}

export function wikiFile(file: string): string {
  return `${ORIGIN}/images/${file}`
}

/**
 * What the picker shows: the icon, small.
 *
 * Always the icon rather than the art, because the grid wants squares of a
 * consistent size and only some skins have art at all.
 */
export function skinIconUrl(skin: SkinEntry, width = 64): string {
  return wikiThumb(skin.icon, width)
}

/**
 * What a profile renders: the posed art when the wiki has it, and the icon when
 * it doesn't.
 *
 * The fallback is not a compromise — the icon source is 1106x1106, so a 400px
 * thumb of it is a real image rather than an upscaled sprite. It means every
 * one of the 673 skins is pickable today instead of only the 414 whose art
 * filename the sync script could match.
 */
export function skinArtUrl(skin: SkinEntry, width = 400): string {
  return wikiThumb(skin.art ?? skin.icon, width)
}

/** The skin every player already owns, and therefore the one that says nothing. */
const DEFAULT_SKIN_NAME = "Classic"

/**
 * A skin to stand in for a player who has not had one curated.
 *
 * The podium reserves a slot for character art bleeding in from the right, and
 * before this only the handful of players an admin had picked a favorite for
 * filled it — so the top three looked like three different components rather
 * than three of the same card. This fills it from something we already know:
 * their main legend.
 *
 * Three rules, in order:
 *
 *  - **Never Classic.** It is the default everyone has, so it is the one skin
 *    that carries no information about the player at all, and it is also the
 *    art already showing in the LegendChip beside it.
 *  - **Posed art first.** `art` is the full-body render and it is what the slot
 *    was designed around; the icon is a square portrait and reads as a sticker.
 *    63 of 69 legends have at least one, and the other four with skins fall
 *    back to the icon rather than rendering nothing — at 12% opacity behind
 *    stats, a cropped portrait is texture either way.
 *  - **Deterministic.** Keyed off the player's id, so a given player always
 *    draws the same skin. A random pick would change the card on every
 *    revalidate, which is motion with no meaning behind it.
 *
 * Returns null for the two legends whose only skin is Classic, and for any
 * legend the catalogue has not caught up with (Aurus today) — the slot then
 * stays empty exactly as it does now.
 */
export function placeholderSkinFor(
  legend: string,
  seed: number
): SkinEntry | null {
  const candidates = skinsForLegend(legend).filter(
    (s) => s.name !== DEFAULT_SKIN_NAME
  )
  if (candidates.length === 0) return null
  const posed = candidates.filter((s) => s.art)
  const pool = posed.length > 0 ? posed : candidates
  return pool[Math.abs(Math.trunc(seed)) % pool.length] ?? null
}
