import catalogue from "@/lib/skins-catalogue.json"

/**
 * The Brawlhalla skin catalogue, read from brawlhalla.wiki.gg.
 *
 * 673 skins across 69 legends in ~50KB of JSON, regenerated by
 * `node scripts/sync-skins.mjs`. A file rather than a table because it is
 * reference data that changes when Blue Mammoth ships a skin — a handful of
 * times a year — and a stale entry costs nothing worse than a skin missing from
 * the picker until someone reruns the script.
 *
 * **We store a URL, not an image.** `profiles.favorite_skin` has always been
 * `{ src, name }`, and the picker writes a wiki thumbnail URL into `src`, so
 * every surface that already renders a favorite skin — profile header, the
 * ranked card, the leaderboard podium — keeps working untouched. Nothing is
 * mirrored, so the catalogue costs no storage and no egress at all.
 *
 * The trade is a dependency on someone else's CDN for user-facing art. It is
 * cached (Cloudflare, 4h) and hotlinking works from a browser, but their
 * filenames are theirs to rename. The cheap hedge, when it matters, is to copy
 * the one chosen image into Blob on save — at most one per player who sets a
 * skin. Until then this is honest about what it is.
 */

const ORIGIN = "https://brawlhalla.wiki.gg"

export interface SkinEntry {
  /** Display name, e.g. "Astral Core". */
  name: string
  /** Wiki filename for the square icon — always present. */
  icon: string
  /** Wiki filename for the posed art. Absent for ~40% of skins. */
  art?: string
}

interface Catalogue {
  generatedAt: string
  legends: Record<string, SkinEntry[]>
}

const DATA = catalogue as Catalogue

/** Legends that have at least one skin, in roster-name form. */
export function skinLegends(): string[] {
  return Object.keys(DATA.legends)
}

export function skinsForLegend(legend: string): SkinEntry[] {
  return DATA.legends[legend] ?? []
}

export function catalogueDate(): string {
  return DATA.generatedAt
}

/**
 * A thumbnail of a wiki file at a given width.
 *
 * MediaWiki renders these on demand and Cloudflare caches them, which is what
 * keeps this cheap: the source art is 962x1280 at ~360KB, a 400px thumb is
 * ~168KB, and a 64px icon is ~8KB. Asking for the original would put a third of
 * a megabyte behind every profile header.
 */
export function wikiThumb(file: string, width: number): string {
  return `${ORIGIN}/images/thumb/${file}/${width}px-${file}`
}

export function wikiFile(file: string): string {
  return `${ORIGIN}/images/${file}`
}

/**
 * What the picker shows: the icon, small.
 *
 * Always the icon rather than the art, because the grid wants squares of a
 * consistent size and only some skins have art at all.
 */
export function skinIconUrl(skin: SkinEntry, width = 64): string {
  return wikiThumb(skin.icon, width)
}

/**
 * What a profile renders: the posed art when the wiki has it, and the icon when
 * it doesn't.
 *
 * The fallback is not a compromise — the icon source is 1106x1106, so a 400px
 * thumb of it is a real image rather than an upscaled sprite. It means every
 * one of the 673 skins is pickable today instead of only the 414 whose art
 * filename the sync script could match.
 */
export function skinArtUrl(skin: SkinEntry, width = 400): string {
  return wikiThumb(skin.art ?? skin.icon, width)
}
